In [94]:
import pandas as pd
import numpy as np

In [95]:
df = pd.read_csv("aqardata_2.csv")
df.head(1)

,mainlocation,sublocation,neighborhood,frontage,purpose,streetwidth,size,Pricepm
0,الرياض,غرب الرياض,حي ظهرة لبن,شمال,سكني,20.0,727,1800

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2951 entries, 0 to 2950
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mainlocation  2951 non-null   object
 1   sublocation   2276 non-null   object
 2   neighborhood  2951 non-null   object
 3   frontage      2951 non-null   object
 4   purpose       2604 non-null   object
 5   streetwidth   2948 non-null   float64
 6   size          2951 non-null   int64
 7   Pricepm       2951 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 184.6+ KB

In [97]:
df_clean = df.dropna(how='any',axis=0)

In [98]:
df_reindexed = df_clean.reset_index(drop=True)

In [99]:
df_reindexed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2031 entries, 0 to 2030
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mainlocation  2031 non-null   object
 1   sublocation   2031 non-null   object
 2   neighborhood  2031 non-null   object
 3   frontage      2031 non-null   object
 4   purpose       2031 non-null   object
 5   streetwidth   2031 non-null   float64
 6   size          2031 non-null   int64
 7   Pricepm       2031 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 127.1+ KB

In [100]:
df_reindexed.head(20)

,mainlocation,sublocation,neighborhood,frontage,purpose,streetwidth,size,Pricepm
0,الرياض,غرب الرياض,حي ظهرة لبن,شمال,سكني,20.0,727,1800
1,الرياض,شمال الرياض,حي العارض,جنوب,تجاري,60.0,5973,2000
2,جدة,شمال جدة,حي الريان,شرق,سكني,20.0,660,2300
3,الرياض,جنوب الرياض,حي السلي,3 شوارع,تجاري,35.0,3200,1500
4,الرياض,شرق الرياض,حي اشبيلية,شمال غربي,سكني,20.0,743,2500
5,جدة,شمال جدة,حي الزهراء,جنوب,سكني,15.0,600,5333
6,الرياض,شرق الرياض,حي الشرق,شمال,سكني,25.0,840,300
7,الرياض,شمال الرياض,حي القيروان,4 شوارع,تجاري,30.0,3000,2900
8,الرياض,شمال الرياض,حي النرجس,شرق,سكني,15.0,525,2200
9,الرياض,شمال الرياض,حي صلاح الدين,3 شوارع,تجاري,80.0,3250,10000
10,جدة,شمال جدة,حي الورود,غرب,سكني أو تجاري,55.0,4160,9500
11,الرياض,شمال الرياض,حي النرجس,شرق,سكني,15.0,1050,2150
12,الرياض,جنوب الرياض,حي المشاعل,3 شوارع,تجاري,30.0,7222,750
13,الرياض,جنوب الرياض,حي الغنامية,غرب,سكني,10.0,480,350
14,الرياض,شمال الرياض,حي بنبان,4 شوارع,سكني أو تجاري,100.0,2610000,350
15,الرياض,شرق الرياض,حي الرمال,3 شوارع,سكني أو تجاري,46.0,13200,2800
16,الرياض,شرق الرياض,حي الخليج,3 شوارع,سكني,15.0,2560,2000
17,الرياض,جنوب الرياض,حي المشاعل,3 شوارع,تجاري,30.0,14570,750
18,الرياض,غرب الرياض,حي عرقة,شرق,سكني,16.0,1200,2200
19,الرياض,شرق الرياض,حي الملز,4 شوارع,سكني أو تجاري,30.0,4980,4000

In [101]:
numeric_columns = ["streetwidth" , "size"]
nominal_columns = ["mainlocation" , "sublocation" , "neighborhood","frontage","purpose"]

In [102]:
df_dummy = pd.get_dummies(df_reindexed)
df_dummy

,streetwidth,size,Pricepm,mainlocation_الرياض,mainlocation_جدة,sublocation_جنوب الرياض,sublocation_جنوب جدة,sublocation_شرق الرياض,sublocation_شمال الرياض,sublocation_شمال جدة,...,frontage_جنوب غربي,frontage_شرق,frontage_شمال,frontage_شمال شرقي,frontage_شمال غربي,frontage_غرب,purpose_تجاري,purpose_سكني,purpose_سكني أو تجاري,purpose_غير محدد
0,20.0,727,1800,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,60.0,5973,2000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,20.0,660,2300,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,1,0,0
3,35.0,3200,1500,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,20.0,743,2500,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,25.0,300,2121,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2027,13.0,750,1100,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2028,60.0,36000,2777,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2029,20.0,354,1200,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2030,15.0,832,2900,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [117]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# df_dummy[numeric_columns] = scaler.fit_transform(df_dummy[numeric_columns])
# df_dummy.head()
df_dummy.columns

Index(['streetwidth', 'size', 'Pricepm', 'mainlocation_الرياض',
       'mainlocation_جدة', 'sublocation_جنوب الرياض', 'sublocation_جنوب جدة',
       'sublocation_شرق الرياض', 'sublocation_شمال الرياض',
       'sublocation_شمال جدة',
       ...
       'frontage_جنوب غربي', 'frontage_شرق', 'frontage_شمال',
       'frontage_شمال شرقي', 'frontage_شمال غربي', 'frontage_غرب',
       'purpose_تجاري', 'purpose_سكني', 'purpose_سكني أو تجاري',
       'purpose_غير محدد'],
      dtype='object', length=162)

In [104]:
X = df_dummy.drop(["Pricepm"], axis=1)
y = df_dummy["Pricepm"]

print(X.shape)
print(y.shape)

(2031, 161)
(2031,)

In [161]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

In [162]:
models = {
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge()
}

In [163]:
for model_name in models:
    model = models[model_name]
    results = cross_validate(model, X, y, cv=10, scoring=['neg_mean_absolute_error', 'neg_root_mean_squared_error'
                                                        ,'r2'], return_train_score=True)

    print(model_name + ": ")
    print("Mean Absolute Error:" , 'train: ', abs(results['train_neg_mean_absolute_error'].mean()),
          '| test: ', abs(results['test_neg_mean_absolute_error'].mean()))
    print("Root Mean Square Error:" , 'train: ', abs(results['train_neg_root_mean_squared_error'].mean()),
          '| test: ', abs(results['test_neg_root_mean_squared_error'].mean()))
    print("R2:" , 'train: ', results['train_r2'].mean(),
          '| test: ', results['test_r2'].mean())
    print("---------------------------------------------------------")

LinearRegression:
Mean Absolute Error: train:  520.5355862635728 | test:  623.1616444880053
Root Mean Square Error: train:  1725.4675162678407 | test:  1938.946343983477
R2: train:  0.4972853727961595 | test:  -0.21017365305029675
---------------------------------------------------------
Ridge:
Mean Absolute Error: train:  536.1958247725402 | test:  605.1869487117235
Root Mean Square Error: train:  1759.4015465329521 | test:  1756.1237765100655
R2: train:  0.47777857018544534 | test:  0.21698086804511232
---------------------------------------------------------

In [206]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, 
                                                    random_state = 5)
print("Training set has {} samples.".format(X_train.shape[0]))
print("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 1624 samples.
Testing set has 407 samples.

Ridge model is producing better results than the LinearRegression

In [215]:
mod = Ridge()
mod.fit(X_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [216]:
import pickle
pickle.dump(mod,open('land_price_prediction_ridge_model.pkl','wb'))