[You Can test the model here](https://ahmad-almosallam.github.io/Machine-Learning-projects/)

# 1- importing the necessary libraries

In [38]:
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

# 2- Gathering, cleaning, assessing data

In [39]:
df = pd.read_csv("aqardata_2.csv")
df.head(1)

  mainlocation sublocation neighborhood  ... streetwidth size  Pricepm
0       الرياض  غرب الرياض  حي ظهرة لبن  ...        20.0  727     1800

[1 rows x 8 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2951 entries, 0 to 2950
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mainlocation  2951 non-null   object
 1   sublocation   2276 non-null   object
 2   neighborhood  2951 non-null   object
 3   frontage      2951 non-null   object
 4   purpose       2604 non-null   object
 5   streetwidth   2948 non-null   float64
 6   size          2951 non-null   int64
 7   Pricepm       2951 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 184.6+ KB

In [41]:
df_clean = df.dropna(how='any',axis=0)

In [42]:
df_reindexed = df_clean.reset_index(drop=True)

In [43]:
df_reindexed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2031 entries, 0 to 2030
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mainlocation  2031 non-null   object
 1   sublocation   2031 non-null   object
 2   neighborhood  2031 non-null   object
 3   frontage      2031 non-null   object
 4   purpose       2031 non-null   object
 5   streetwidth   2031 non-null   float64
 6   size          2031 non-null   int64
 7   Pricepm       2031 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 127.1+ KB

In [44]:
df_reindexed.head()

  mainlocation  sublocation neighborhood  ... streetwidth  size  Pricepm
0       الرياض   غرب الرياض  حي ظهرة لبن  ...        20.0   727     1800
1       الرياض  شمال الرياض    حي العارض  ...        60.0  5973     2000
2          جدة     شمال جدة    حي الريان  ...        20.0   660     2300
3       الرياض  جنوب الرياض     حي السلي  ...        35.0  3200     1500
4       الرياض   شرق الرياض   حي اشبيلية  ...        20.0   743     2500

[5 rows x 8 columns]

In [45]:
numeric_columns = ["streetwidth" , "size"]
nominal_columns = ["mainlocation" , "sublocation" , "neighborhood","frontage","purpose"]

#3- Preprocessing

In [46]:
df_dummy = pd.get_dummies(df_reindexed)
df_dummy

      streetwidth   size  ...  purpose_سكني أو تجاري  purpose_غير محدد
0            20.0    727  ...                      0                 0
1            60.0   5973  ...                      0                 0
2            20.0    660  ...                      0                 0
3            35.0   3200  ...                      0                 0
4            20.0    743  ...                      0                 0
...           ...    ...  ...                    ...               ...
2026         25.0    300  ...                      0                 0
2027         13.0    750  ...                      0                 0
2028         60.0  36000  ...                      0                 0
2029         20.0    354  ...                      0                 0
2030         15.0    832  ...                      0                 0

[2031 rows x 162 columns]

In [47]:
X = df_dummy.drop(["Pricepm"], axis=1)
y = df_dummy["Pricepm"]

print(X.shape)
print(y.shape)

(2031, 161)
(2031,)

# 4- Training and Evaluation Result

In [48]:
models = {
    "LinearRegression":LinearRegression(),
    "Ridge":Ridge()
}

In [49]:
for model_name in models:
    model = models[model_name]
    results = cross_validate(model, X, y, cv=10, scoring=['neg_mean_absolute_error', 'neg_root_mean_squared_error'
                                                        ,'r2'], return_train_score=True)

    print(model_name + ": ")
    print("Mean Absolute Error:" , 'train: ', abs(results['train_neg_mean_absolute_error'].mean()),
          '| test: ', abs(results['test_neg_mean_absolute_error'].mean()))
    print("Root Mean Square Error:" , 'train: ', abs(results['train_neg_root_mean_squared_error'].mean()),
          '| test: ', abs(results['test_neg_root_mean_squared_error'].mean()))
    print("R2:" , 'train: ', results['train_r2'].mean(),
          '| test: ', results['test_r2'].mean())
    print("---------------------------------------------------------")

LinearRegression:
Mean Absolute Error: train:  520.5355862357036 | test:  623.1616444939298
Root Mean Square Error: train:  1725.467516267841 | test:  1938.9463439626506
R2: train:  0.4972853727961595 | test:  -0.21017365303816496
---------------------------------------------------------
Ridge:
Mean Absolute Error: train:  536.1958247725402 | test:  605.1869487117234
Root Mean Square Error: train:  1759.4015465329521 | test:  1756.1237765100655
R2: train:  0.47777857018544523 | test:  0.21698086804511255
---------------------------------------------------------